---
- name: Installation des Services Web et Base de Donnees
  hosts: all
  become: yes
  tasks:
    # --- CONFIGURATION WEBSERVER ---
    - name: Installation Apache sur le Webserver
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: inventory_hostname == '192.168.100.10'

    - name: Page d'accueil personnalisee
      copy:
        content: "<h1>PROJET TERMINE AVEC SUCCES : Pipeline final avec NAT et Services Ajoute.</h1><p>Deploye par Ansible - Architecture IaC.</p>"
        dest: /var/www/html/index.html
      when: inventory_hostname == '192.168.100.10'

    # --- CONFIGURATION DBSERVER ---
    - name: Installation MariaDB et dépendances Python
      apt:
        name: 
          - mariadb-server
          - python3-pymysql  # INDISPENSABLE pour le module mysql_user
        state: present
        update_cache: yes
      when: inventory_hostname == '192.168.10.10'

    - name: S'assurer que MariaDB écoute sur toutes les interfaces
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      when: inventory_hostname == '192.168.10.10'
      notify: Restart MariaDB

    - name: Créer l'utilisateur vagrant pour l'accès distant
      mysql_user:
        name: vagrant
        password: "votre_mot_de_passe"
        priv: '*.*:ALL'
        host: '%'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock # Permet à Ansible de se connecter sans mot de passe root via le socket
      when: inventory_hostname == '192.168.10.10'

  handlers:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted